services:
  server:
    image: jekyll/jekyll:4
    container_name: dadocm
    ports:
      - '4000:4000'
    environment:
      - TZ=America/New_York
      - JEKYLL_ENV=production
    volumes:
      - '.:/code'
    working_dir: /code
    command: >
      bash -c "bundle install &&
               bundle exec jekyll serve --force_polling --config _config.yml --host 0.0.0.0"